#tomcat的配置
server:
  port: 8082
  servlet:
    path: /
#配置jdbc    不需要配置驱动,直接根据url识别mysql.可以直接使用驱动,pom导入就可以
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/day01
    username: root
    password: 123456
# 配置mybatis  pom文件引入依赖引入的是通用的mapper 简单的增删改查不需要写代码,直接使用其中的方法
mybatis:
  type-aliases-package: cn.hxzy.pojo